### ISSUE TITLE
CI failures for X64 and linux

### ISSUE THREAD

**Issue by siddhipai** [strongloop/loopback-oracle-installer#17]
see [#16](https://github.com/strongloop/loopback-oracle-installer/pull/16)

**Comment by rashmihunt** [comment]
There are not test cases in loopback-oracle-installer because it's a installer code for loopback-connector oracle module. The only time a developer would run 'npm i' on loopback-oracle-installer  would be in their dev environment when they are fixing an issue in loopback-oracle-installer . In this dev env,  loopback-oracle-installer depends on loopback-oracle-builder to be it's pier node module (checked out at the same as  loopback-oracle-installer module).  In CI setup,  loopback-oracle-builder is not available because it's not a dev env, hence the CI failures.

Ideally, CI shouldn't be running loopback-oracle-installer. Instead this CI should just run the CI for dependent module which is loopback-connector-oracle which will in-turn do 'npm i loopback-oracle-installer' which will test any change developer has made to loopback-oracle-installer.  loopback-oracle-installer CI should ideally only kick off CI for loopback-connector-oracle.

**Comment by dhmlau** [comment]
CI failed for node 0.10 and 0.12.  Since LB 3.x does not support these 2 node versions, we can fix CI by updating the `package.json` accordingly.

**Comment by dhmlau** [comment]
Closing as resolved. 
Looking at the last merged PR, all CI passed.
